# Generated by Django 4.1 on 2022-08-17 15:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=255)),
                ('title', models.CharField(default='Book', max_length=255, null=True)),
                ('published_year', models.CharField(blank=True, max_length=255, null=True)),
                ('pages', models.IntegerField(blank=True, null=True)),
                ('acquired', models.BooleanField(default=True)),
                ('thumbnail', models.TextField(blank=True)),
                ('authors', models.ManyToManyField(blank=True, related_name='books', to='authors.author')),
            ],
        ),
    ]
