# Generated by Django 4.1 on 2022-08-19 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0004_remove_author_user'),
        ('books', '0003_alter_book_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(blank=True, default='Sample Author', related_name='books', to='authors.author'),
        ),
    ]
