# Generated by Django 4.1 on 2022-08-28 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profilefollowing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilefollowing',
            options={'ordering': ['-created']},
        ),
        migrations.AddConstraint(
            model_name='profilefollowing',
            constraint=models.UniqueConstraint(fields=('user_id', 'following_user_id'), name='unique_followers'),
        ),
    ]
