# Generated by Django 4.1 on 2022-08-17 15:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=225, unique=True)),
                ('wiki_url', models.URLField(max_length=500, null=True)),
            ],
        ),
    ]
